; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.50727.1 

	TITLE	c:\Users\owner\documents\visual studio 2012\Projects\ClearUsingPointers\ClearUsingPointers\ClearUsingPointers.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?ClearUsingPointers@@YAXPAHH@Z			; ClearUsingPointers
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?ClearUsingPointers@@YAXPAHH@Z
_TEXT	SEGMENT
_p$ = -8						; size = 4
_array$ = 8						; size = 4
_size$ = 12						; size = 4
?ClearUsingPointers@@YAXPAHH@Z PROC			; ClearUsingPointers, COMDAT
; File c:\users\owner\documents\visual studio 2012\projects\clearusingpointers\clearusingpointers\clearusingpointers.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 9
	mov	eax, 4
	imul	eax, 0
	add	eax, DWORD PTR _array$[ebp]
	mov	DWORD PTR _p$[ebp], eax
	jmp	SHORT $LN3@ClearUsing
$LN2@ClearUsing:
	mov	eax, DWORD PTR _p$[ebp]
	add	eax, 4
	mov	DWORD PTR _p$[ebp], eax
$LN3@ClearUsing:
	mov	eax, DWORD PTR _size$[ebp]
	mov	ecx, DWORD PTR _array$[ebp]
	lea	edx, DWORD PTR [ecx+eax*4]
	cmp	DWORD PTR _p$[ebp], edx
	jae	SHORT $LN4@ClearUsing
; Line 10
	mov	eax, DWORD PTR _p$[ebp]
	mov	DWORD PTR [eax], 0
	jmp	SHORT $LN2@ClearUsing
$LN4@ClearUsing:
; Line 11
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?ClearUsingPointers@@YAXPAHH@Z ENDP			; ClearUsingPointers
_TEXT	ENDS
END
